replicaCount: 1
image:
  repository: hvmzx/react-article-display
  tag: 03c2a5d023911e6ae9f525c306b2ccec85181431
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  name: null
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - paths:
        - /
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
