replicaCount: 1
image:
  repository: hvmzx/react-article-display
  tag: b9ce50c51fb0ec85d51a4a669f8ea36417cd8818
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  name: null
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - paths:
        - /
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
