replicaCount: 1
image:
  repository: hvmzx/react-article-display
  tag: 81039efa645325df07e1894a17e02404c18a0759
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  name: null
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - paths:
        - /
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
